### ISSUE TITLE
Vulnerability in ramp-transformer with jackson-databind

### ISSUE THREAD

**Issue by derekbelrose** [rmap-project/rmap-transformer#1]
Hi Karen,

Please see the following vulnerability and determine if an update of the library is warranted.

https://github.com/rmap-project/rmap-transformer/network/alert/pom.xml/com.fasterxml.jackson.core:jackson-databind/open

If we are no longer using this repository, it might help to mark it as archived and no longer maintained.

**Comment by karenhanson** [comment]
This repository is deprecated, changing it to archived.
